# Generated by Django 2.2.16 on 2022-08-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220818_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
