# Generated by Django 2.2.16 on 2022-08-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
