# Generated by Django 2.2.16 on 2022-08-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_auto_20220819_2118"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AlterModelOptions(
            name="title",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"]},
        ),
    ]
